<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- 雷达部件 -->
<!-- 支架设计 -->
<!-- 
    参数
    11.支架尺寸：半径，高度，
    12.关节偏移量：xyz
    21.雷达尺寸
    22.雷达偏移量
 -->
 <xacro:property name="suport_radius" value="0.01" />
 <xacro:property name="suport_length" value="0.15" />
 <xacro:property name="laser_radius" value="0.03" />
 <xacro:property name="laser_length" value="0.05" />

 <xacro:property name="joinit_suport_x" value="0" />
 <xacro:property name="joinit_suport_y" value="0" />
 <xacro:property name="joinit_suport_z" value="${base_length / 2 + suport_length / 2}" />
 <xacro:property name="joinit_laser_x" value="0" />
 <xacro:property name="joinit_laser_y" value="0" />
 <xacro:property name="joinit_laser_z" value="${base_length / 2 + laser_length / 2}" />

<link>
    <geometry>
        


    </geometry>
</link>
<!-- 雷达 -->





</robot >