<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 属性定义 -->
    <xacro:property name="footprint_radius" value="0.001" />

    <!-- 1.添加 base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <!-- 底盘 -->
    <!-- 
        形状：圆柱
        半径：0.1m
        高度：0.08m
        离地：0.15m
     -->
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length / 2 + lidi}" />
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>

            <origin xyz="0 0 0" rpy="0 0 0" />

            <material name="baselink_color">
                <color rgba="0.5 1.0 0.2 0.5" />
            </material>
        </visual>
    </link>
    <!-- 2-2.joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint"  />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${base_joint_z}" rpy="0 0 0" />
    </joint>

    <!-- 属性调用 -->

        <!-- 驱动轮 -->
    <!-- 
        形状：圆柱
        半径：0.035m
        长度：0.015m
     -->
     <!-- link -->
     <xacro:property name ="wheel_radius" value="0.035" />
     <xacro:property name ="wheel_length" value="0.015" />
     <xacro:property name ="PI" value="3.1415927" />
     <xacro:property name ="wheel_joint_z" value="${-(base_length / 2 +lidi - wheel_radius)}" />

     <xacro:macro name="wheel_func" params="wheel_name flag">

        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>

                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />

                <material name="wheel_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>

        <!-- joint -->
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link"  />
            <child link="${wheel_name}_wheel" />
            <origin xyz="0.0 ${0.1 * flag} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>

     </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <!-- 万向轮 -->
    <!-- 
        现状：球
        半径：0.0075m
     -->
    <xacro:property name="small_wheel_radius" value="0.0075" />
    <xacro:property name="small_joint_z" value="${-(base_length / 2 + lidi - small_wheel_radius)}" />


    <xacro:macro name="small_wheel_func" params="small_wheel_name flag">
     <!-- 属性 -->
    <link name="${small_wheel_name}_wheel">
        <visual>
            <geometry>
                <sphere radius="${small_wheel_radius}" />
            </geometry>

            <origin xyz="0 0 0" rpy="0 0 0" />

            <material name="wheel_color">
                <color rgba="0 0 0 0.3" />
            </material>
        </visual>
    </link>

    <joint name="${small_wheel_name}2link" type="continuous">
        <parent link="base_link"  />
        <child link="${small_wheel_name}_wheel" />
        <origin xyz="${0.08*flag} 0.0 ${small_joint_z}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint> 

    </xacro:macro >

    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />

    <!-- 算术运算 -->






</robot>