<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- 摄像头部件 -->
<!-- 参数 -->
<!-- 
    1.形状：立方体，连杆
    2.参数：高度，宽度,厚度
    3.关节属性 x y z
 -->
<xacro:property name="camera_length" value="0.02" /><!-- 厚度（x方向） -->
<xacro:property name="camera_width" value="0.05" /><!-- 宽度（y方向） -->
<xacro:property name="camera_height" value="0.05" /><!-- 高度（z方向） -->
<xacro:property name="joint_camera_x" value="0.08" />
<xacro:property name="joint_camera_y" value="0" />
<xacro:property name="joint_camera_z" value="${base_length / 2 + camera_height / 2}" />
<link name="camera">
    <visual>
        <geometry>
            <box size="${camera_length} ${camera_width} ${camera_height}" />
        </geometry>

        <material name="black">
            <color rgba="0 0 0 0.7" />
        </material>
    </visual>
</link >
<joint name="camera2base" type="fixed">
    <parent link ="base_link" />
    <child link="camera" />
    <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0" />
</joint>



</robot >